### ISSUE TITLE
Not able to set light attributes

### ISSUE THREAD

**Issue by storm84** [lpgera/dirigera#12]
not sure if it has to do do with a firmware update or something but I'm not able to change any state of my lamps.
I'm able to to use the get operations like list all lights and get info for a single light by id, but when i try to call `setIsOn` or `setLightLevel` it does not work.

I'm calling it using the example code from the README

when calling `setIsOn` it fails silently but for `setLightLevel` it fails with the following error:

```
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

HTTPError [DirigeraError]: {"error":"Error","message":"\"attributes\" does not match any of the allowed types"}
    at Request.<anonymous> (file:///<removed>node_modules/.pnpm/got@14.4.5/node_modules/got/dist/source/as-promise/index.js:92:42)
    at Object.onceWrapper (node:events:633:26)
    at Request.emit (node:events:530:35)
    at Request._onResponseBase (file:///<removed>/node_modules/.pnpm/got@14.4.5/node_modules/got/dist/source/core/index.js:609:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Request._onResponse (file:///<removed>/node_modules/.pnpm/got@14.4.5/node_modules/got/dist/source/core/index.js:649:13) {
  input: undefined,
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1733089324492,
    socket: 1733089324493,
    lookup: 1733089324494,
    connect: 1733089324494,
    secureConnect: 1733089324709,
    upload: 1733089324710,
    response: 1733089324752,
    end: 1733089324761,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 1,
      tcp: 0,
      tls: 215,
      request: 1,
      firstByte: 42,
      download: 9,
      total: 269
    }
  },
  options: Options {
    _unixOptions: undefined,
    _internals: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: undefined,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: '[{"attributes":{"lightLevel":"100"},"transitionTime":"2000"}]',
      form: undefined,
      json: undefined,
      cookieJar: undefined,
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [ [Function (anonymous)] ],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        authorization: 'Bearer <removed>',
        'content-type': 'application/json',
        accept: 'application/json',
        'content-length': '61',
        'accept-encoding': 'gzip, deflate, br'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'PATCH',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: false,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: undefined,
      resolveBodyOnly: false,
      isStream: false,
      responseType: 'text',
      url: URL {},
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: false
    },
    _merging: false,
    _init: [
      {
        prefixUrl: 'https://[<ip removed>]:8443/v1',
        headers: {
          authorization: 'Bearer <removed>'
        },
        https: { rejectUnauthorized: false },
        hooks: { beforeError: [ [Function (anonymous)] ] }
      },
      {
        json: [ { attributes: [Object], transitionTime: '2000' } ],
        method: 'patch'
      }
    ]
  },
  [cause]: {}
}

Node.js v22.11.0

```

**Comment by lpgera** [comment]
>       body: '[{"attributes":{"lightLevel":"100"},"transitionTime":"2000"}]',

Based on this line, I assume you're trying to send the `lightLevel` and `transitionTime` attributes as strings, is that true? They both must be numbers, otherwise you'll receive the `"attributes" does not match any of the allowed types` error from your Dirigera gateway.

**Comment by storm84** [comment]
As far as I understand it should be sent in as numbers, but it might as well be me doing something wrong as JS/TS is not my usual languages to code in.

here is the piece of code that calls the client 

```typescript
program
  .command("set-light-level <id> <level> [transition-time]")
  .description("set the light level")
  .action(
    async (id: string, level: number, transitionTime: number | undefined) => {
      var client = await ClientFactory.CreateClient();
      await client.lights.setLightLevel({
        id: id,
        lightLevel: level,
        transitionTime: transitionTime,
      });
    },
  );
```

**Comment by lpgera** [comment]
If you're using the `commander` package here then it does indeed call your action with all command line arguments as strings, so your own type definitions are wrong on the action's callback function's signature.

You can check it by adding a `console.log(typeof level)` and a `console.log(typeof transitionTime)` before calling `.setLightLevel()`, and you'll see that both of them will print out "string" to your console.

By the way, I'm pretty sure that most languages provide command line arguments as strings by default, and it's almost always your responsibility to validate and parse them, so this is not a JS specific behavior.

I'm closing this issue, because it is not related to this library, but feel free to open a new one if you find something.

**Comment by storm84** [comment]
Thanks for your input, and sorry for missing that part. Yes I'm aware that most languages handles cmd arguments as strings by default, but i thought this was handled with some TS magic or at least should brake the code before hitting the client call.
Any ways thanks again and thanks for your work with this client

**Comment by lpgera** [comment]
No worries!

I believe you're not protected by TypeScript in this case as the library you use to provide the arguments to your code does not have full TypeScript support by default. See their documentation here: https://www.npmjs.com/package/commander#typescript
