### ISSUE TITLE
client.lights.setLightLevel returns an uncaught error that doesnt make sense

### ISSUE THREAD

**Issue by kiterwork** [lpgera/dirigera#5]
Hello again, figured i would split the issues ive been facing as they seem to be unrelated.

When using the code below (example code from the documentation) i get the error shown below the code.

```
client.lights.setLightLevel({    
    id: 'deviceid',
    lightLevel: 10,
    transitionTime: 5000,
})
```

```
Error:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HTTPError [DirigeraError]: {"error":"Error","message":"\"attributes\" does not match any of the allowed types"}
    at Request.<anonymous> (file:///C:/Users/kiter/Desktop/ikea/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:627:26)
    at Request.emit (node:events:524:35)
    at Request._onResponseBase (file:///C:/Users/kiter/Desktop/ikea/node_modules/got/dist/source/core/index.js:603:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///C:/Users/kiter/Desktop/ikea/node_modules/got/dist/source/core/index.js:645:13) {
  input: undefined,
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  
  ```
  
  
  Ill be happy to share more data where needed, but im not sure what you could need. I could of course set this functionality up using my own timer and setting the lightlevel lower every x seconds, but figured this ought to be fixed for other people using the lib.

**Comment by kiterwork** [comment]
It looks like setLightLevel does not work at all, even while only running 

```
await client.lights.setLightLevel({
    id: 'id',
    lightLevel: 1,
})
```

**Comment by kiterwork** [comment]
```
await client.lights.setLightLevel({
        id: 'id',
        lightLevel: 100,
        transitionTime: 25000,
    })
    
    for whatever reason this now works... Im lost
